In [3]:
import pandas as pd
import numpy as np


In [5]:
a = np.array([2,5,6,7,8,3,2,1])

In [6]:
a

array([2, 5, 6, 7, 8, 3, 2, 1])

In [8]:
a.shape

(8,)

In [63]:
a = np.eye(3, 4, 1)
b = np.eye(3, 4, 0) * 2
c = a+b

In [66]:
a

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [71]:
ansver = np.array([])

In [72]:
ansver

array([], dtype=float64)

In [73]:
ansver[0] = 8
ansver[1] = 9

IndexError: index 0 is out of bounds for axis 0 with size 0

In [67]:
for i in range(3):
    print(a[i])

[0. 1. 0. 0.]
[0. 0. 1. 0.]
[0. 0. 0. 1.]


In [68]:
type(a[1])

numpy.ndarray

In [64]:
mat = c

In [65]:
mat

array([[2., 1., 0., 0.],
       [0., 2., 1., 0.],
       [0., 0., 2., 1.]])

In [40]:
mat.size

12

In [41]:
mat = mat.reshape(mat.size,1)


In [43]:
mat

array([[2.],
       [1.],
       [0.],
       [0.],
       [0.],
       [2.],
       [1.],
       [0.],
       [0.],
       [0.],
       [2.],
       [1.]])

In [46]:
c

array([[2., 1., 0., 0.],
       [0., 2., 1., 0.],
       [0., 0., 2., 1.]])

In [50]:
c.cumsum()

array([2., 3., 3., 3., 3., 5., 6., 6., 6., 6., 8., 9.])

In [51]:
from urllib.request import urlopen
import numpy as np

filename = "https://stepic.org/media/attachments/lesson/16462/boston_houses.csv"
f = urlopen(filename)

In [56]:
file = np.loadtxt(f, skiprows=1, delimiter=',')

In [59]:
print(file)

[[28.7      0.02985  0.      ...  0.458    6.43     6.0622 ]
 [22.9      0.08829 12.5     ...  0.524    6.012    5.5605 ]
 [27.1      0.14455 12.5     ...  0.524    6.172    5.9505 ]
 ...
 [23.9      0.06076  0.      ...  0.573    6.976    2.1675 ]
 [22.       0.10959  0.      ...  0.573    6.794    2.3889 ]
 [11.9      0.04741  0.      ...  0.573    6.03     2.505  ]]


In [62]:
print(file.mean(axis=0))

[22.45848303  3.64926263 11.44111776  0.06986028  0.55545649  6.27884032
  3.78072455]


In [ ]:
perfect = False
while not perfect:
    perfect = True
    for e in examples:
        if Predict(e) != Target(e):
            perfect = False
            if Predict(e) == 0:
                w = w + e # просто складываем вектор весов и вектор 
            if Predict(e) == 1:
                w = w - e
            